-dontwarn org.conscrypt.**
-dontwarn javax.naming.**
-keep class com.squareup.wire.** { *; }
-keep class app.fyreplace.protos.** { *; }
-keepnames class app.fyreplace.fyreplace.ui.views.navigation.**
