name: Publishing

on:
  push:
    branches:
      - develop
      - hotfix/*
      - release/*
    tags:
      - v*.*.*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: google-play-store
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Cache gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up keystore
        env:
          KEYSTORE_B64: ${{ secrets.KEYSTORE_B64 }}
        run: echo $KEYSTORE_B64 | base64 --decode > /tmp/fyreplace.keystore

      - name: Set up Google services
        env:
          GOOGLE_SERVICES_B64: ${{ secrets.GOOGLE_SERVICES_B64 }}
        run: echo $GOOGLE_SERVICES_B64 | base64 --decode > app/google-services.json

      - name: Build APKs
        env:
          KEYSTORE_PATH: /tmp/fyreplace.keystore
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: Build bundles
        env:
          KEYSTORE_PATH: /tmp/fyreplace.keystore
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew bundleRelease

      - uses: actions/upload-artifact@v3
        with:
          name: Fyreplace.apk
          path: app/build/outputs/apk/google/release/*.apk
          if-no-files-found: error

      - uses: actions/upload-artifact@v3
        with:
          name: Fyreplace-libre.apk
          path: app/build/outputs/apk/libre/release/*.apk
          if-no-files-found: error

      - uses: actions/upload-artifact@v3
        with:
          name: Fyreplace.aab
          path: app/build/outputs/bundle/googleRelease/*.aab
          if-no-files-found: error

      - uses: actions/upload-artifact@v3
        with:
          name: Fyreplace-libre.aab
          path: app/build/outputs/bundle/libreRelease/*.aab
          if-no-files-found: error

  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    environment: google-play-store
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up artifact directory
        run: mkdir -p build

      - uses: actions/download-artifact@v3
        with:
          name: Fyreplace.aab
          path: build

      - name: Set up Google service account
        env:
          GCLOUD_SERVICE_ACCOUNT_CREDENTIALS_B64: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_CREDENTIALS_B64 }}
        run: echo $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS_B64 | base64 --decode > build/google-service-account.json

      - name: Upload bundle to Google Play
        run: |
          case "${{ github.ref_name }}" in
          v*.*.*)
            export track=beta;;
          hotfix/*)
            export track=beta;;
          *)
            export track=internal;;
          esac
          fastlane supply \
            --track $track \
            --changes_not_sent_for_review true \
            --json_key build/google-service-account.json \
            --aab build/*.aab \
            --package_name ${{ secrets.PACKAGE_NAME }}
